language: node_js
node_js:
    - '12'

dist: trusty
sudo: false # better for performance

before_install:
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO
    - AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
    - echo $AUTHOR_NAME
    - export TZ=Europe/Brussels
    - git config --global user.email "deploy@travis-ci.org"
    - git config --global user.name "Travis CI"
    - git remote add github https://$GH_TOKEN@github.com/BetterLineage/android_prebuilts_prebuiltapks.git

env:
    global:
        - LOGS_DIR=/tmp/android_prebuilts_prebuiltapks/logs
        - LOGS_FILE=/tmp/android_prebuilts_prebuiltapks/logs/build-perf.log

install:
    # Create file & folder for Travis logs
    # cfr scripts/_travis-fold.sh
    - mkdir -p $LOGS_DIR
    - touch $LOGS_DIR/build-perf.log

branches:
    only:
        - master

script:
    - bash ./scripts/update-packages.sh
    - bash ./scripts/ci/print-logs.sh
